=== tuegum/web/out/production/XML01/dtd/student.dtd
<!ELEMENT students (stu*)>
<!ELEMENT stu (name,age,sex)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT age (#PCDATA) >
<!ELEMENT sex (#PCDATA)>
<!ATTLIST stu number ID #REQUIRED>

=== tuegum/web/XML/dtd/student.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE students SYSTEM "student.dtd">
<students>
    <stu number="s001">
        <name></name>
        <age></age>
        <sex></sex>
    </stu>

    <stu number="s002">
        <name></name>
        <age></age>
        <sex></sex>
    </stu>

</students>

=== tuegum/web/out/production/XML01/dtd/student.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE students SYSTEM "student.dtd">
<students>
    <stu number="s001">
        <name>tom</name>
        <age>12</age>
        <sex>male</sex>
    </stu>

    <stu number="s002">
        <name>jarry</name>
        <age>8</age>
        <sex>female</sex>
    </stu>
</students>
